### ISSUE TITLE
Incorrect motion when exporting to Daz Studio

### ISSUE THREAD

**Issue by SlimeVRX** [butaixianran/Blender-Vmd-Retargeting#24] opened 2022-12-22 02:28 UTC
**Blender version:**  
- Blender 3.1

**Plugin Blender version:**  
- VMD Retargeting 1.19.1
- DAZ Importer 1.6.1.0824

**Model type:**  
- Daz Studio 4.21 Pro

**Issue:**  

In Blender, the movement is very accurate but when exporting to Daz Studio the motion is not accurate. I followed your video tutorial.

**Offer at least one of following for testing:**  
Video:  [Link Video](https://youtu.be/Z4XuUD-UGZo)
File (Export to Daz Studio .duf + Blender + VMD): [Link File](https://drive.google.com/file/d/1TNWML1ilxTo5bgISRC9d0Om62cQ5Mv4H/view?usp=sharing)

**Comment by butaixianran** [comment] 2022-12-22 12:55
I tried your blender file.  

With my character, this vmd motion can be exported to Daz Studio all correctly.   
![frame_447_daz](https://user-images.githubusercontent.com/5558722/209133586-ce289848-d62b-46e6-9f52-1d2e129810ff.jpg)  

Your blender file works fine. The problem is not at blender side. It is at Daz side.   

In Daz Studio, Genesis 8 have hidden and locked x, y, z rotation properties on every bone. As following picture shows.
![daz_g8_locked_rotation_channel](https://user-images.githubusercontent.com/5558722/209137093-bb9db91f-0f26-4531-8232-71a6b4ef9c11.jpg)   

The exported daz pose preset need to use those properties. So, you need to make them visible then unlock those x,y,z rotation properties on every bone of your character in Daz Studio, before you load that pose preset. As following picture shows.
![daz_g8_unlocked_rotation_channel](https://user-images.githubusercontent.com/5558722/209138695-5770dca9-8587-4154-a5ac-96910ac1f3d1.jpg)


It is insane to do this on every Daz Character. So, what I did is, I load a Default G8 character, unlock those rotation channels, and save it as a character preset. Then, I always use this preset, as my Default G8 model. All my new character is created based on this character preset. So, I only need to unlock those things once.  

This is a pure Daz tip, and not just for importing mmd motion. To import any motion, for example, a bvh file, you need to unlock those xyz rotation properties.

**Comment by SlimeVRX** [comment] 2022-12-22 15:33
Thank you for your quick response, 

I will learn and follow your instructions. Thank you very much!

**Comment by SlimeVRX** [comment] 2022-12-23 06:44
Hi @butaixianran 

I checked unlocking those x,y,z rotation channels on every bone, but still not working.
Can you try again with a brand-new character?

Please help me! Thank you very much!

Video: [Link Video](https://youtu.be/7KczZCybAM4)

**Comment by SlimeVRX** [comment] 2022-12-23 09:14
I wonder if I have any problem using DAZ3D 4.21 version. In your tests use DAZ3D 4.20 version.

**Comment by SlimeVRX** [comment] 2022-12-23 10:32
**Blender version:**  
- Blender 3.3 (not 3.1)

**Plugin Blender version:**  
- VMD Retargeting 1.19.1
- DAZ Importer 1.6.2 (not 1.6.1)

**Model type:**
- Daz Studio 4.21 Pro

Update: I have successfully exported from Blender to Daz Studio with Genesis 9. Video: [Link Video](https://youtu.be/Gy4wO5SClYo)
There is one more problem, VMD Retargeting can't import Facial (Mouth and Eyes) into Genesis 9

Update: I failed to export from Blender to Daz Studio with Genesis 8

**Comment by butaixianran** [comment] 2022-12-23 14:47
Daz version doesn't matter.

Check your character again. If you unlocked those bones, it will work. Also, turn off rotation limit as video tutorial shows.

Following is a new G8 default female model, at frame 447:

Before unlock them:
![before_unlock](https://user-images.githubusercontent.com/5558722/209354392-c960497a-3cc5-4a19-b818-2698ce949bf8.jpg)

After unlock them:
![after_unlock](https://user-images.githubusercontent.com/5558722/209354405-d452c6fd-d50f-4bd9-b502-8ba1afa47e63.jpg)

**Comment by SlimeVRX** [comment] 2022-12-23 15:23
> Daz version doesn't matter.

Yes, My Daz3D studio is 4.21 Pro. I don't install older versions.

> Check your character again. If you unlocked those bones, it will work. Also, turn off rotation limit as video tutorial shows.

Please see video: [Link Video](https://youtu.be/7KczZCybAM4). I followed your video tutorials. I checked unlocking those x,y,z rotation channels on every bone, but still not working.

**Comment by butaixianran** [comment] 2022-12-23 18:45
hi, your video shows, you didn't unlock them at all.

Those rotation properties are hidden properties, you didn't even set them visible.

search in google to learn how to set hidden properties visible in Daz

**Comment by SlimeVRX** [comment] 2022-12-23 19:42
Thank you! I understand, I will search Google to learn how to set hidden channels in Daz3D

Thank you very much!

**Comment by SlimeVRX** [comment] 2022-12-24 03:23
Update: I have set hidden channels visible in Daz. Model was working correctly.

Thank you for your enthusiastic support!

**Comment by butaixianran** [comment] 2022-12-31 14:13
reopen this issue as a tutorial for other users

**Comment by SlimeVRX** [comment] 2023-01-03 01:24
Yes, I will write a tutorial

**Comment by SlimeVRX** [comment] 2023-01-03 04:46
I write a tutorial on how to solve the problem

I don't remember exactly which method I used but in my note there are these 2 instructions:
- [Link1](https://renderguide.com/daz3d-how-to-hide-scene-parts-that-are-not-selectable)
- [Link2](https://www.daz3d.com/forums/discussion/301786/hide-multiple-items)

![image](https://user-images.githubusercontent.com/99313947/210290709-babc185c-fc89-4d55-85ec-71de50e3f1fc.png)

Note: Look for "Show Hidden ..." and enable all options that have it

Tutorial Video: [Link Video](https://www.youtube.com/watch?v=qptCff0kqqs&ab_channel=TinNguy%E1%BB%85n)

**Comment by butaixianran** [comment] 2023-01-03 05:31
Do not close this issue.

**Comment by butaixianran** [comment] 2023-01-23 14:12
For any other users, you don't need to watch any video to get this done. 

Just check "Show Hidden properties" in Daz Studio, so those x,y,z rotation properties will be visible. **Then unlock them on every bone** of your character.

**Comment by butaixianran** [comment] 2023-01-31 11:15
Close this issue since I have added a tutorial at the end of document page. Also a Daz script for this, so people don't need to do it manually anymore.

**Closed as completed by butaixianran** 2023-01-31 11:15 UTC
